### PR TITLE
feat(typescript-config): create declaration files on build of ts files

### PR DESCRIPTION
**Pull request by sgrigorev**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes # 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Comment by alexkvak** [comment]
with these changes even non-library project will emit declarations that is not necessary, is it OK?

**Comment by sgrigorev** [comment]
> with these changes even non-library project will emit declarations that is not necessary, is it OK?

Not sure. What do you think about the separate config file for libraries ?

**Comment by alexkvak** [comment]
> > with these changes even non-library project will emit declarations that is not necessary, is it OK?
> 
> Not sure. What do you think about the separate config file for libraries ?

yes, but maybe this is some kind of over-engineering for only one config option?

**Comment by sgrigorev** [comment]
Agree. Let's separate them if there will more differences.

**Pull request closed without merging**
